// Mocks generated by Mockito 5.1.0 from annotations
// in pick_a_sit/test/features/pick_seat/domain/usecases/book_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pick_a_sit/core/errors/failure.dart' as _i6;
import 'package:pick_a_sit/features/pick_seat/domain/entities/bus_line_entity.dart'
    as _i7;
import 'package:pick_a_sit/features/pick_seat/domain/entities/seat_entity.dart'
    as _i8;
import 'package:pick_a_sit/features/pick_seat/domain/entities/user_entity.dart'
    as _i9;
import 'package:pick_a_sit/features/pick_seat/domain/repositories/pick_seat_repository.dart'
    as _i2;
import 'package:pick_a_sit/features/pick_seat/domain/usecases/book_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePickSeatRepository_0 extends _i1.Fake
    implements _i2.PickSeatRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [BookUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookUsecase extends _i1.Mock implements _i4.BookUsecase {
  MockBookUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PickSeatRepository get pickSeatRepository =>
      (super.noSuchMethod(Invocation.getter(#pickSeatRepository),
          returnValue: _FakePickSeatRepository_0()) as _i2.PickSeatRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
          _i4.BookUsecaseParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, bool>>.value(
                  _FakeEither_1<_i6.Failure, bool>()))
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [PickSeatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickSeatRepository extends _i1.Mock
    implements _i2.PickSeatRepository {
  MockPickSeatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.BusLineEntity>>> getBusLines() =>
      (super.noSuchMethod(Invocation.method(#getBusLines, []),
          returnValue:
              Future<_i3.Either<_i6.Failure, List<_i7.BusLineEntity>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.BusLineEntity>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.BusLineEntity>>>);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.SeatEntity>>> getSeats(
          String? busLine) =>
      (super.noSuchMethod(Invocation.method(#getSeats, [busLine]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i8.SeatEntity>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i8.SeatEntity>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i8.SeatEntity>>>);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> book(
          String? busLine, int? seatNumber, _i9.UserEntity? userEntity) =>
      (super.noSuchMethod(
              Invocation.method(#book, [busLine, seatNumber, userEntity]),
              returnValue: Future<_i3.Either<_i6.Failure, bool>>.value(
                  _FakeEither_1<_i6.Failure, bool>()))
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
